apiVersion: apps/v1
kind: Deployment
metadata:
  name: cardmarket
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cardmarket
  template:
    metadata:
      labels:
        app: cardmarket
    spec:
      containers:
        - name: cardmarket
          image: ghcr.io/harshadeevi/cardmarket:v1.0.7
          ports:
            - containerPort: 8080
