
name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: docker build -t cardmarket:${{ github.ref_name }} ./cardmarket
      - run: docker save cardmarket:${{ github.ref_name }} -o cardmarket-${{ github.ref_name }}.tar
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: Release for ${{ github.ref_name }}
          files: cardmarket-${{ github.ref_name }}.tar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
